#!/usr/bin/env python
# -*- coding: utf-8 -*-

from sklearn.model_selection import train_test_split
from TaxiFareModel.data import get_data, clean_data
from TaxiFareModel.trainer import Trainer

N = 10_000
df = get_data(nrows=N)
df = clean_data(df)
y = df["fare_amount"]
X = df.drop("fare_amount", axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
trainer = Trainer(X_train, y_train)
trainer.run()
trainer.evaluate(X_test, y_test)
